@extends('layouts.app')

@section('title', 'Dashboard | Property Management')
@section('page-heading', 'System Overview')

@section('content')
    @php
        $categoryStops = [];
        $categoryPosition = 0;
        foreach ($categoryChart as $category) {
            $nextPosition = $categoryPosition + $category['percentage'];
            $categoryStops[] = "{$category['color']} {$categoryPosition}% {$nextPosition}%";
            $categoryPosition = $nextPosition;
        }
        $categoryGradient = $categoryStops === [] ? '#e2e8f0' : 'conic-gradient('.implode(', ', $categoryStops).')';
        $maximumCampusAssets = max(1, (int) $campusChart->max('count'));
        $trendPoints = $trendChart->map(fn (array $point): string => $point['x'].','.$point['y'])->implode(' ');
        $selectedCampus = $filterOptions['campuses']->firstWhere('id', (int) ($filters['campus_id'] ?? 0));
        $dateLabels = ['current_financial_year' => 'Current financial year', 'last_30_days' => 'Last 30 days', 'last_quarter' => 'Last quarter', 'last_12_months' => 'Last 12 months'];
    @endphp

    <div class="flex flex-col gap-6">
        <section class="overflow-hidden rounded-2xl bg-busitema-blue shadow-sm dark:bg-blue-950">
            <div class="relative px-6 py-7 sm:px-8">
                <div class="absolute -top-20 right-6 size-56 rounded-full bg-white/10 blur-3xl" aria-hidden="true"></div>
                <div class="absolute -right-12 -bottom-28 size-56 rounded-full bg-busitema-gold/15 blur-3xl" aria-hidden="true"></div>
                <div class="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
                    <div><p class="text-xs font-semibold tracking-[0.14em] text-busitema-gold uppercase">System Administrator</p><h2 class="mt-2 text-2xl font-semibold text-white sm:text-3xl">University assets and system operations</h2><p class="mt-2 max-w-3xl text-sm leading-6 text-white/70">Live asset records, account activity, operational attention items, and platform status across Property Management.</p></div>
                    <span class="inline-flex w-fit items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-medium text-white/80"><span class="size-2 rounded-full bg-emerald-400"></span>Live data · Updated {{ $updatedAt->diffForHumans() }}</span>
                </div>
            </div>
        </section>

        <form class="rounded-xl border border-border bg-white p-5 shadow-sm" method="GET" action="{{ route('dashboard') }}" aria-labelledby="dashboard-filters-heading">
            <div class="flex flex-col gap-4 xl:flex-row xl:items-end">
                <div class="xl:w-44 xl:shrink-0"><h2 class="text-base font-semibold text-heading" id="dashboard-filters-heading">Dashboard filters</h2><p class="mt-1 text-xs leading-5 text-body-text">Selections refresh the overview.</p></div>
                <div class="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
                    <label class="flex flex-col gap-1.5 text-xs font-semibold text-body-text">Campus<select class="min-h-10 rounded-lg border border-border bg-white px-3 text-sm font-medium text-heading outline-none focus:border-busitema-blue" name="campus_id" onchange="this.form.submit()"><option value="">All campuses</option>@foreach ($filterOptions['campuses'] as $campus)<option value="{{ $campus->id }}" @selected((int) ($filters['campus_id'] ?? 0) === $campus->id)>{{ $campus->name }}</option>@endforeach</select></label>
                    <label class="flex flex-col gap-1.5 text-xs font-semibold text-body-text">Asset Type<select class="min-h-10 rounded-lg border border-border bg-white px-3 text-sm font-medium text-heading outline-none focus:border-busitema-blue" name="asset_type_id" onchange="this.form.submit()"><option value="">All asset types</option>@foreach ($filterOptions['assetTypes'] as $type)<option value="{{ $type->id }}" @selected((int) ($filters['asset_type_id'] ?? 0) === $type->id)>{{ $type->name }}</option>@endforeach</select></label>
                    <label class="flex flex-col gap-1.5 text-xs font-semibold text-body-text">Status<select class="min-h-10 rounded-lg border border-border bg-white px-3 text-sm font-medium text-heading outline-none focus:border-busitema-blue" name="status" onchange="this.form.submit()"><option value="">All statuses</option>@foreach (['active' => 'Active / In use', 'maintenance' => 'Under maintenance', 'poor_critical' => 'Poor / Critical', 'retired' => 'Retired / Disposed'] as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></label>
                    <label class="flex flex-col gap-1.5 text-xs font-semibold text-body-text">Faculty / Department<select class="min-h-10 rounded-lg border border-border bg-white px-3 text-sm font-medium text-heading outline-none focus:border-busitema-blue" name="org_unit_id" onchange="this.form.submit()"><option value="">All units</option>@foreach ($filterOptions['orgUnits'] as $unit)<option value="{{ $unit->id }}" @selected((int) ($filters['org_unit_id'] ?? 0) === $unit->id)>{{ $unit->name }}</option>@endforeach</select></label>
                    <label class="flex flex-col gap-1.5 text-xs font-semibold text-body-text">Date Range<select class="min-h-10 rounded-lg border border-border bg-white px-3 text-sm font-medium text-heading outline-none focus:border-busitema-blue" name="date_range" onchange="this.form.submit()">@foreach ($dateLabels as $value => $label)<option value="{{ $value }}" @selected($filters['date_range'] === $value)>{{ $label }}</option>@endforeach</select></label>
                </div>
                <a class="inline-flex min-h-10 shrink-0 items-center justify-center rounded-lg border border-border px-4 text-sm font-semibold text-busitema-deep-blue hover:border-busitema-blue hover:text-busitema-blue" href="{{ route('dashboard') }}">Reset</a>
            </div>
        </form>

        <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="System administration key performance indicators">
            <x-stat-card label="Total Registered Assets" :value="number_format($metrics['totalAssets'])" :detail="'Across '.number_format($campusChart->count()).' campuses in this view'" tone="blue"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7.5 12 3l8 4.5M5 9v9l7 3 7-3V9M12 12l8-4.5M12 12 4 7.5M12 12v9" /></svg></x-stat-card>
            <x-stat-card label="Total System Users" :value="number_format($metrics['totalUsers'])" :detail="number_format($metrics['activeUsers']).' active user accounts'" tone="purple"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87" /></svg></x-stat-card>
            <x-stat-card label="Assets Under Maintenance" :value="number_format($metrics['underMaintenance'])" :detail="number_format($metrics['highPriorityMaintenance']).' high-priority work items'" tone="orange"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m14.7 6.3 3-3a4 4 0 0 1-5 5l-7.4 7.4a2.1 2.1 0 0 0 3 3l7.4-7.4a4 4 0 0 0 5-5l-3 3-3-3Z" /></svg></x-stat-card>
            <x-stat-card label="Poor / Critical Assets" :value="number_format($metrics['poorCritical'])" :detail="$metrics['poorCriticalPercentage'].'% of filtered assets'" tone="red"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 3 2.5 20h19L12 3Zm0 6v5M12 17.5h.01" /></svg></x-stat-card>
            <x-stat-card label="Active Agreements" :value="number_format($metrics['activeAgreements'])" detail="Current leases, allocations, and MOUs" tone="green"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M7 3h8l4 4v14H7V3Zm8 0v5h4M10 13h6M10 17h6" /></svg></x-stat-card>
            <x-stat-card label="Pending Approvals" :value="number_format($metrics['pendingApprovals'])" detail="Awaiting administrator review" tone="gold"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 11 12 14 22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11" /></svg></x-stat-card>
            <x-stat-card label="Expiring Documents" :value="number_format($metrics['expiringDocuments'])" detail="Due within the next 90 days" tone="orange"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M6 3v3M18 3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v14H4V6a1 1 0 0 1 1-1Z" /></svg></x-stat-card>
            <x-stat-card label="Outstanding Alerts" :value="number_format($metrics['outstandingAlerts'])" :detail="number_format($metrics['criticalAlerts']).' items marked urgent or critical'" tone="red"><svg class="size-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" /></svg></x-stat-card>
        </section>

        <section class="grid gap-6 xl:grid-cols-5">
            <article class="rounded-xl border border-border bg-white p-6 shadow-sm xl:col-span-2">
                <div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-heading">Assets by Category</h2><p class="mt-1 text-sm text-body-text">Portfolio composition</p></div><span class="text-xs font-semibold text-busitema-blue">{{ number_format($metrics['totalAssets']) }} total</span></div>
                @if ($categoryChart->isEmpty())
                    <div class="mt-6 flex min-h-44 items-center justify-center rounded-xl bg-light-background text-center text-sm text-body-text">No asset records match these filters.</div>
                @else
                    <div class="mt-6 flex flex-col items-center gap-6 sm:flex-row xl:flex-col 2xl:flex-row"><div class="relative size-44 shrink-0 rounded-full" role="img" aria-label="Asset distribution by category" style="background: {{ $categoryGradient }}"><div class="absolute inset-8 flex flex-col items-center justify-center rounded-full bg-white"><span class="text-2xl font-semibold text-heading">{{ number_format($metrics['totalAssets']) }}</span><span class="text-xs text-body-text">assets</span></div></div><div class="grid w-full gap-3">@foreach ($categoryChart as $category)<div class="flex items-center justify-between gap-3 text-sm"><span class="flex min-w-0 items-center gap-2 text-body-text"><span class="size-2.5 shrink-0 rounded-full" style="background-color: {{ $category['color'] }}"></span><span class="truncate">{{ $category['name'] }}</span></span><span class="shrink-0 font-semibold text-heading">{{ $category['percentage'] }}% <small class="font-normal text-body-text">· {{ number_format($category['count']) }}</small></span></div>@endforeach</div></div>
                @endif
            </article>

            <article class="rounded-xl border border-border bg-white p-6 shadow-sm xl:col-span-3">
                <div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-heading">Assets by Campus</h2><p class="mt-1 text-sm text-body-text">Registered assets across university locations</p></div><span class="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-semibold text-busitema-blue">{{ $selectedCampus?->name ?? 'All campuses' }}</span></div>
                <div class="mt-7 flex h-56 items-end gap-3 border-b border-border sm:gap-5" role="img" aria-label="Registered assets by campus">@forelse ($campusChart as $campus)<div class="group flex h-full min-w-0 flex-1 flex-col items-center justify-end gap-2"><span class="text-[0.65rem] font-semibold text-heading sm:text-xs">{{ number_format($campus['count']) }}</span><div class="w-full max-w-12 rounded-t-md bg-busitema-blue transition group-hover:bg-busitema-deep-blue dark:bg-sky-500" style="height: {{ max(2, round(($campus['count'] / $maximumCampusAssets) * 88)) }}%"></div><span class="w-full truncate pb-2 text-center text-[0.62rem] text-body-text sm:text-xs">{{ $campus['name'] }}</span></div>@empty<p class="m-auto text-sm text-body-text">No campuses are configured.</p>@endforelse</div>
            </article>
        </section>

        <section class="grid gap-6 xl:grid-cols-5">
            <article class="rounded-xl border border-border bg-white p-6 shadow-sm xl:col-span-3">
                <div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-lg font-semibold text-heading">Asset Registration Trend</h2><p class="mt-1 text-sm text-body-text">Monthly registrations in the latest 12-month window</p></div><span class="text-xs font-semibold text-busitema-blue">{{ number_format($trendChart->sum('count')) }} records shown</span></div>
                <div class="mt-6 overflow-hidden" role="img" aria-label="Monthly asset registrations"><svg class="h-56 w-full" viewBox="0 0 720 230" preserveAspectRatio="none"><defs><linearGradient id="registration-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#1e73be" stop-opacity="0.22" /><stop offset="100%" stop-color="#1e73be" stop-opacity="0" /></linearGradient></defs><g stroke="#e5e4e7"><line x1="42" y1="20" x2="704" y2="20" /><line x1="42" y1="72" x2="704" y2="72" /><line x1="42" y1="124" x2="704" y2="124" /><line x1="42" y1="176" x2="704" y2="176" /></g><polygon points="42,198 {{ $trendPoints }} 704,198" fill="url(#registration-area)" /><polyline points="{{ $trendPoints }}" fill="none" stroke="#1e73be" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" />@foreach ($trendChart as $point)<circle cx="{{ $point['x'] }}" cy="{{ $point['y'] }}" r="4" fill="#fff" stroke="#1e73be" stroke-width="3"><title>{{ $point['label'] }}: {{ $point['count'] }}</title></circle>@endforeach</svg><div class="grid grid-cols-6 gap-2 text-center text-[0.65rem] text-body-text sm:grid-cols-12 sm:text-xs">@foreach ($trendChart as $point)<span class="{{ $loop->index < 6 ? 'hidden sm:block' : '' }}">{{ $point['label'] }}</span>@endforeach</div></div>
            </article>
            <article class="rounded-xl border border-border bg-white p-6 shadow-sm xl:col-span-2"><div><h2 class="text-lg font-semibold text-heading">Asset Condition / Status</h2><p class="mt-1 text-sm text-body-text">Current condition in the filtered portfolio</p></div><div class="mt-7 flex h-4 overflow-hidden rounded-full bg-slate-100" role="img" aria-label="Asset condition distribution">@foreach ($conditionChart as $condition)<span class="{{ $condition['color'] }}" style="width: {{ $condition['percentage'] }}%"></span>@endforeach</div><div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">@foreach ($conditionChart as $condition)<div class="rounded-lg bg-light-background p-3"><p class="flex items-center gap-2 text-xs text-body-text"><span class="size-2.5 rounded-full {{ $condition['color'] }}"></span>{{ $condition['label'] }}</p><p class="mt-1.5 text-lg font-semibold text-heading">{{ number_format($condition['count']) }} <small class="font-normal text-body-text">({{ $condition['percentage'] }}%)</small></p></div>@endforeach</div><p class="mt-5 rounded-lg border-l-4 border-red-500 bg-red-50 px-4 py-3 text-xs leading-5 text-body-text"><span class="font-semibold text-red-700">Review recommended:</span> {{ number_format($metrics['poorCritical']) }} assets carry a poor or critical condition flag.</p></article>
        </section>

        <section class="grid gap-6 xl:grid-cols-3">
            <article class="overflow-hidden rounded-xl border border-border bg-white shadow-sm xl:col-span-2"><div class="flex items-start justify-between gap-4 border-b border-border px-6 py-5"><div><h2 class="text-lg font-semibold text-heading">Attention Required</h2><p class="mt-1 text-sm text-body-text">Items approaching deadlines or awaiting action</p></div><span class="flex size-8 shrink-0 items-center justify-center rounded-full bg-red-50 text-sm font-semibold text-red-700">{{ $attentionTotal }}</span></div><div class="grid divide-y divide-border md:grid-cols-2 md:divide-x md:divide-y-0">@foreach ($attentionItems->chunk(3) as $items)<div class="divide-y divide-border">@foreach ($items as $item)<div class="flex items-center gap-4 px-6 py-4"><span class="flex size-9 shrink-0 items-center justify-center rounded-lg text-sm font-semibold {{ $item['classes'] }}">{{ $item['count'] }}</span><div><p class="text-sm font-semibold text-heading">{{ $item['title'] }}</p><p class="mt-0.5 text-xs leading-5 text-body-text">{{ $item['detail'] }}</p></div></div>@endforeach</div>@endforeach</div></article>
            <div class="grid gap-6 sm:grid-cols-2 xl:grid-cols-1">
                <article class="rounded-xl border border-border bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-heading">User Accounts</h2><p class="mt-1 text-sm text-body-text">Account status overview</p></div><span class="text-xl font-semibold text-heading">{{ number_format($metrics['totalUsers']) }}</span></div><div class="mt-5 flex h-3 overflow-hidden rounded-full bg-slate-100">@foreach ($userChart as $userStatus)<span class="{{ $userStatus['color'] }}" style="width: {{ $metrics['totalUsers'] === 0 ? 0 : round(($userStatus['count'] / $metrics['totalUsers']) * 100) }}%"></span>@endforeach</div><div class="mt-5 grid grid-cols-3 gap-3 text-center">@foreach ($userChart as $userStatus)<div><p class="text-lg font-semibold {{ $userStatus['text'] }}">{{ number_format($userStatus['count']) }}</p><p class="text-xs text-body-text">{{ $userStatus['label'] }}</p></div>@endforeach</div></article>
                <article class="rounded-xl border border-border bg-white p-6 shadow-sm"><div class="flex items-start justify-between gap-4"><div><h2 class="text-lg font-semibold text-heading">System Health</h2><p class="mt-1 text-sm text-body-text">Live database and queue status</p></div><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">{{ $health['database'] }}</span></div><dl class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-lg bg-light-background p-3"><dt class="text-xs text-body-text">Database</dt><dd class="mt-1 font-semibold text-heading">{{ $health['database'] }}</dd></div><div class="rounded-lg bg-light-background p-3"><dt class="text-xs text-body-text">Queued jobs</dt><dd class="mt-1 font-semibold text-heading">{{ number_format($health['queuedJobs']) }}</dd></div><div class="rounded-lg bg-light-background p-3"><dt class="text-xs text-body-text">Failed jobs</dt><dd class="mt-1 font-semibold {{ $health['failedJobs'] ? 'text-red-700' : 'text-heading' }}">{{ number_format($health['failedJobs']) }}</dd></div><div class="rounded-lg bg-light-background p-3"><dt class="text-xs text-body-text">Last activity</dt><dd class="mt-1 text-sm font-semibold text-heading">{{ $health['lastActivity'] ? \Carbon\Carbon::parse($health['lastActivity'])->diffForHumans() : 'None yet' }}</dd></div></dl></article>
            </div>
        </section>

        <section class="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-border px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-semibold text-heading">Recent System Activity / Audit Trail</h2><p class="mt-1 text-sm text-body-text">Latest recorded actions across Property Management</p></div><a class="self-start rounded-full bg-light-background px-3 py-1.5 text-xs font-medium text-body-text hover:text-busitema-blue" href="{{ route('audit-trail.index') }}">View full audit trail</a></div>
            <div class="overflow-x-auto"><table class="w-full min-w-4xl text-left text-sm"><thead class="bg-light-background text-xs font-semibold tracking-wide text-body-text uppercase"><tr><th class="px-6 py-3">Date & Time</th><th class="px-6 py-3">User</th><th class="px-6 py-3">Action</th><th class="px-6 py-3">Module</th><th class="px-6 py-3">Reference</th><th class="px-6 py-3">Result</th></tr></thead><tbody class="divide-y divide-border">@forelse ($recentActivity as $activity)<tr class="transition hover:bg-light-background/70"><td class="whitespace-nowrap px-6 py-4 text-body-text" title="{{ $activity->created_at->format('d M Y H:i:s') }}">{{ $activity->created_at->diffForHumans() }}</td><td class="whitespace-nowrap px-6 py-4 font-semibold text-heading">{{ $activity->user_name ?? 'System Service' }}</td><td class="px-6 py-4 text-body-text">{{ $activity->description }}</td><td class="whitespace-nowrap px-6 py-4 text-body-text">{{ str(class_basename($activity->auditable_type ?? 'System'))->headline() }}</td><td class="whitespace-nowrap px-6 py-4 font-medium text-busitema-blue">{{ $activity->auditable_id ? '#'.$activity->auditable_id : '—' }}</td><td class="whitespace-nowrap px-6 py-4"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Recorded</span></td></tr>@empty<tr><td class="px-6 py-10 text-center text-body-text" colspan="6">No activity has been recorded for the selected filters.</td></tr>@endforelse</tbody></table></div>
        </section>
    </div>
@endsection
