<div class="mx-auto flex max-w-7xl flex-col gap-6" x-data="{ confirmArchive: false }">
    <nav class="flex flex-wrap items-center gap-2 text-sm text-body-text" aria-label="Breadcrumb"><a class="font-medium hover:text-busitema-blue" href="{{ route("operations.{$module}.index") }}">{{ $design['title'] }}</a><span aria-hidden="true">/</span><span class="font-semibold text-heading">{{ $record['reference'] }}</span></nav>

    <section class="overflow-hidden rounded-2xl bg-busitema-blue shadow-sm transition-colors dark:bg-blue-950">
        <div class="relative px-6 py-7 sm:px-8">
            <div class="absolute -top-16 right-4 size-52 rounded-full bg-white/10 blur-3xl" aria-hidden="true"></div>
            <div class="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
                <div><div class="flex flex-wrap items-center gap-3"><p class="text-xs font-semibold tracking-[0.14em] text-busitema-gold uppercase">{{ $design['singular'] }} · {{ $record['reference'] }}</p><span class="rounded-full bg-white/10 px-2.5 py-1 text-xs font-semibold text-white">{{ $record['status'] }}</span></div><h2 class="mt-3 text-2xl font-semibold text-white sm:text-3xl">{{ $record['name'] }}</h2><p class="mt-2 text-sm text-white/75">{{ $record['campus'] }} · {{ $record['primary'] }}</p></div>
                <div class="flex flex-wrap gap-2"><button class="inline-flex min-h-11 items-center rounded-lg border border-white/20 bg-white/10 px-4 text-sm font-semibold text-white transition hover:bg-white/15" type="button">Print record</button><a class="inline-flex min-h-11 items-center rounded-lg bg-busitema-gold px-5 text-sm font-semibold text-busitema-navy transition hover:bg-busitema-yellow" href="{{ route("operations.{$module}.edit", ['record' => $record['reference']]) }}">Edit {{ $design['singular'] }}</a></div>
            </div>
        </div>
    </section>

    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Record provenance">
        @foreach ([['Created By', $record['createdBy']], ['Created At', $record['createdAt']], ['Last Updated By', $record['updatedBy']], ['Last Updated At', $record['updatedAt']]] as [$label, $value])
            <article class="rounded-xl border border-border bg-white p-5 shadow-sm"><p class="text-xs font-semibold tracking-wide text-body-text uppercase">{{ $label }}</p><p class="mt-2 text-sm font-semibold text-heading">{{ $value }}</p></article>
        @endforeach
    </section>

    @if (isset($design['workflow']))
        <section class="rounded-xl border border-border bg-white p-6 shadow-sm">
            <div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-semibold tracking-[0.12em] text-busitema-blue uppercase">Maintenance workflow</p><h2 class="mt-1.5 text-xl font-semibold text-heading">Problem Reported → Assessment → Approval → Assignment → Repair → Final Inspection → Closed</h2></div><span class="w-fit rounded-full bg-blue-50 px-3 py-1.5 text-xs font-semibold text-busitema-blue">Current: {{ $design['workflow'][$design['activeWorkflowStep']] }}</span></div>
            <ol class="mt-6 grid gap-2 sm:grid-cols-4 xl:grid-cols-7">
                @foreach ($design['workflow'] as $step)
                    <li class="relative rounded-lg border p-3 {{ $loop->index <= $design['activeWorkflowStep'] ? 'border-busitema-blue/40 bg-blue-50' : 'border-border bg-light-background' }}"><span class="flex size-7 items-center justify-center rounded-full text-xs font-bold {{ $loop->index < $design['activeWorkflowStep'] ? 'bg-emerald-500 text-white' : ($loop->index === $design['activeWorkflowStep'] ? 'bg-busitema-blue text-white' : 'bg-slate-200 text-body-text') }}">{{ $loop->index < $design['activeWorkflowStep'] ? '✓' : $loop->iteration }}</span><p class="mt-2 text-xs font-semibold leading-5 text-heading">{{ $step }}</p></li>
                @endforeach
            </ol>
        </section>
    @endif

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_20rem]">
        <div class="flex flex-col gap-6">
            @foreach ($design['detailSections'] as [$sectionTitle, $items])
                <section class="rounded-xl border border-border bg-white p-6 shadow-sm sm:p-8">
                    <div class="border-b border-border pb-5"><p class="text-xs font-semibold tracking-[0.12em] text-busitema-blue uppercase">Record overview</p><h2 class="mt-1.5 text-xl font-semibold text-heading">{{ $sectionTitle }}</h2></div>
                    <dl class="mt-6 grid gap-x-8 gap-y-5 sm:grid-cols-2">
                        @foreach ($items as [$label, $value])
                            <div class="border-b border-border pb-4"><dt class="text-xs font-semibold tracking-wide text-body-text uppercase">{{ $label }}</dt><dd class="mt-1.5 text-sm font-semibold leading-6 text-heading">{{ $value }}</dd></div>
                        @endforeach
                    </dl>
                </section>
            @endforeach

            @if ($module === 'beneficiaries')
                <section class="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
                    <div class="border-b border-border px-6 py-5"><h2 class="text-lg font-semibold text-heading">Charges, payments, and balances</h2><p class="mt-1 text-sm text-body-text">Illustrative financial ledger linked to the active allocation.</p></div>
                    <div class="overflow-x-auto"><table class="w-full min-w-3xl text-left text-sm"><thead class="bg-light-background text-xs font-semibold text-body-text uppercase"><tr><th class="px-6 py-3">Date</th><th class="px-6 py-3">Description</th><th class="px-6 py-3">Charge</th><th class="px-6 py-3">Payment</th><th class="px-6 py-3">Balance</th></tr></thead><tbody class="divide-y divide-border"><tr><td class="px-6 py-4 text-body-text">01 Aug 2026</td><td class="px-6 py-4 font-semibold text-heading">August lease charge</td><td class="px-6 py-4 text-body-text">UGX 4,800,000</td><td class="px-6 py-4 text-body-text">—</td><td class="px-6 py-4 font-semibold text-red-600">UGX 8,000,000</td></tr><tr><td class="px-6 py-4 text-body-text">04 Aug 2026</td><td class="px-6 py-4 font-semibold text-heading">Payment receipt RC-88421</td><td class="px-6 py-4 text-body-text">—</td><td class="px-6 py-4 text-emerald-700">UGX 4,800,000</td><td class="px-6 py-4 font-semibold text-heading">UGX 3,200,000</td></tr></tbody></table></div>
                </section>
            @endif

            @if ($module === 'inspections')
                <section class="rounded-xl border border-border bg-white p-6 shadow-sm"><div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-lg font-semibold text-heading">Photographs &amp; reports</h2><p class="mt-1 text-sm text-body-text">Evidence supporting findings, follow-up, and resolution.</p></div><button class="min-h-10 rounded-lg border border-busitema-blue px-4 text-sm font-semibold text-busitema-blue" type="button">Upload evidence</button></div><div class="mt-5 grid gap-4 sm:grid-cols-3"><div class="flex aspect-video items-center justify-center rounded-lg bg-blue-50 text-xs font-semibold text-busitema-blue">Photo 01 · DB labels</div><div class="flex aspect-video items-center justify-center rounded-lg bg-orange-50 text-xs font-semibold text-orange-700">Photo 02 · Damaged socket</div><div class="flex aspect-video items-center justify-center rounded-lg border border-border bg-light-background text-xs font-semibold text-body-text">Signed inspection report.pdf</div></div></section>
            @endif

            @if ($module === 'documents')
                <section class="rounded-xl border border-border bg-white p-6 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-lg font-semibold text-heading">New version upload</h2><p class="mt-1 text-sm text-body-text">Add a replacement while retaining the complete version history.</p></div><button class="min-h-10 rounded-lg bg-busitema-gold px-4 text-sm font-semibold text-busitema-navy" type="button">Upload new version</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="flex flex-col gap-2 text-sm font-semibold text-heading">Version label<input class="min-h-11 rounded-lg border border-border bg-white px-3 font-normal" type="text" value="4.0"></label><label class="flex flex-col gap-2 text-sm font-semibold text-heading">Replacement file<input class="min-h-11 rounded-lg border border-border bg-white px-3 py-2 font-normal" type="file"></label></div></section>
            @endif

            <section class="overflow-hidden rounded-xl border border-border bg-white shadow-sm">
                <div class="border-b border-border px-6 py-5"><h2 class="text-lg font-semibold text-heading">Activity / Audit History</h2><p class="mt-1 text-sm text-body-text">Chronological administrative activity for this record.</p></div>
                <ol class="divide-y divide-border px-6">
                    <li class="flex gap-4 py-5"><span class="mt-1 flex size-8 shrink-0 items-center justify-center rounded-full bg-blue-50 text-busitema-blue"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z" /></svg></span><div class="min-w-0 flex-1"><p class="text-sm font-semibold text-heading">Record updated</p><p class="mt-1 text-xs leading-5 text-body-text">{{ $record['updatedBy'] }} updated operational details and reviewed the current status.</p></div><time class="shrink-0 text-xs text-body-text">{{ $record['updatedAt'] }}</time></li>
                    <li class="flex gap-4 py-5"><span class="mt-1 flex size-8 shrink-0 items-center justify-center rounded-full bg-amber-50 text-amber-700"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 8v4l3 2M12 3a9 9 0 1 0 9 9" /></svg></span><div class="min-w-0 flex-1"><p class="text-sm font-semibold text-heading">Status reviewed</p><p class="mt-1 text-xs leading-5 text-body-text">The System Administrator reviewed approvals, ownership, dates, and supporting evidence.</p></div><time class="shrink-0 text-xs text-body-text">29 Aug 2026</time></li>
                    <li class="flex gap-4 py-5"><span class="mt-1 flex size-8 shrink-0 items-center justify-center rounded-full bg-emerald-50 text-emerald-700"><svg class="size-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m5 12 4 4L19 6" /></svg></span><div class="min-w-0 flex-1"><p class="text-sm font-semibold text-heading">Record created</p><p class="mt-1 text-xs leading-5 text-body-text">{{ $record['createdBy'] }} created the original {{ strtolower($design['singular']) }} record.</p></div><time class="shrink-0 text-xs text-body-text">{{ $record['createdAt'] }}</time></li>
                </ol>
            </section>
        </div>

        <aside class="flex flex-col gap-4 xl:sticky xl:top-6 xl:self-start">
            <section class="rounded-xl border border-border bg-white p-5 shadow-sm"><p class="text-xs font-semibold tracking-[0.12em] text-busitema-blue uppercase">Super Admin controls</p><h2 class="mt-1.5 text-lg font-semibold text-heading">Manage record</h2><div class="mt-4 flex flex-col gap-2">@if ($module === 'agreements')<a class="inline-flex min-h-10 items-center justify-between rounded-lg border border-border px-3 text-sm font-semibold text-busitema-deep-blue hover:border-busitema-blue hover:text-busitema-blue" href="{{ route('operations.agreements.approval', ['record' => $record['reference']]) }}"><span>Approve agreement</span><span aria-hidden="true">→</span></a><a class="inline-flex min-h-10 items-center justify-between rounded-lg border border-border px-3 text-sm font-semibold text-busitema-deep-blue hover:border-busitema-blue hover:text-busitema-blue" href="{{ route('operations.agreements.renewal', ['record' => $record['reference']]) }}"><span>Start renewal</span><span aria-hidden="true">→</span></a><a class="inline-flex min-h-10 items-center justify-between rounded-lg border border-border px-3 text-sm font-semibold text-busitema-deep-blue hover:border-busitema-blue hover:text-busitema-blue" href="{{ route('operations.agreements.termination', ['record' => $record['reference']]) }}"><span>Start termination</span><span aria-hidden="true">→</span></a>@endif @foreach ($design['quickActions'] as $action)@continue($module === 'agreements' && in_array($action, ['Approve agreement', 'Start renewal', 'Start termination'], true))<button class="inline-flex min-h-10 items-center justify-between rounded-lg border px-3 text-left text-sm font-semibold transition {{ str_contains(strtolower($action), 'archive') ? 'border-red-200 text-red-600 hover:bg-red-50' : 'border-border text-busitema-deep-blue hover:border-busitema-blue hover:text-busitema-blue' }}" type="button" @if (str_contains(strtolower($action), 'archive')) @click="confirmArchive = ! confirmArchive" @endif><span>{{ $action }}</span><span aria-hidden="true">→</span></button>@endforeach</div><div x-cloak x-show="confirmArchive" x-transition class="mt-4 rounded-lg border border-red-200 bg-red-50 p-3"><p class="text-xs leading-5 text-red-700">Archive control preview only. The record will not be changed.</p></div></section>
            <section class="rounded-xl border border-border bg-white p-5 shadow-sm"><h2 class="text-base font-semibold text-heading">Record context</h2><dl class="mt-4 flex flex-col gap-4 text-sm"><div><dt class="text-xs text-body-text">Campus</dt><dd class="mt-1 font-semibold text-heading">{{ $record['campus'] }}</dd></div><div><dt class="text-xs text-body-text">Status</dt><dd class="mt-1"><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $record['statusClass'] }}">{{ $record['status'] }}</span></dd></div><div><dt class="text-xs text-body-text">Reference</dt><dd class="mt-1 font-semibold text-busitema-blue">{{ $record['reference'] }}</dd></div><div><dt class="text-xs text-body-text">Access scope</dt><dd class="mt-1 font-semibold text-heading">All campuses · Super Admin</dd></div></dl></section>
            <section class="rounded-xl border border-border bg-white p-5 shadow-sm"><div class="flex items-center justify-between gap-3"><h2 class="text-base font-semibold text-heading">Related documents</h2><span class="rounded-full bg-light-background px-2 py-1 text-xs font-semibold text-body-text">4</span></div><div class="mt-4 flex flex-col gap-3"><button class="flex items-center gap-3 rounded-lg border border-border p-3 text-left" type="button"><span class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-red-50 text-xs font-bold text-red-700">PDF</span><span><span class="block text-xs font-semibold text-heading">Primary supporting record</span><span class="mt-0.5 block text-[0.68rem] text-body-text">Current version</span></span></button><button class="flex items-center gap-3 rounded-lg border border-border p-3 text-left" type="button"><span class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-blue-50 text-xs font-bold text-busitema-blue">IMG</span><span><span class="block text-xs font-semibold text-heading">Photographic evidence</span><span class="mt-0.5 block text-[0.68rem] text-body-text">3 files</span></span></button></div></section>
            <a class="inline-flex min-h-11 items-center justify-center rounded-lg border border-border bg-white px-4 text-sm font-semibold text-busitema-deep-blue shadow-sm transition hover:border-busitema-blue hover:text-busitema-blue" href="{{ route("operations.{$module}.index") }}">Back to {{ $design['title'] }}</a>
        </aside>
    </div>
</div>
