@extends('layouts.app')
@section('title', 'Computer Labs | Property Management')
@section('portal-label', auth()->user()->role?->name === 'System Administrator' ? 'Property Management Administration · ICT Assets' : 'IT Technician Workspace')
@section('page-heading', 'Computer Labs')
@section('user-role', auth()->user()->role?->name ?? 'IT Technician')
@section('sidebar') @include('technician.partials.sidebar') @endsection

@section('content')
<div class="space-y-6">
    @include('technician.partials.messages')
    <section class="rounded-xl border border-border bg-white p-5 shadow-sm"><form method="GET" class="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><label class="text-sm font-semibold text-heading">Lab Name<input name="name" value="{{ request('name') }}" class="mt-1.5 w-full rounded-lg border border-border bg-white px-3 py-2.5 font-normal"></label><label class="text-sm font-semibold text-heading">Campus<select name="campus_id" class="mt-1.5 w-full rounded-lg border border-border bg-white px-3 py-2.5 font-normal"><option value="">All campuses</option>@foreach($filterCampuses as $campus)<option value="{{ $campus->id }}" @selected(request('campus_id')==$campus->id)>{{ $campus->name }}</option>@endforeach</select></label><label class="text-sm font-semibold text-heading">Responsible Technician<select name="technician_id" class="mt-1.5 w-full rounded-lg border border-border bg-white px-3 py-2.5 font-normal"><option value="">All technicians</option>@foreach($filterTechnicians as $user)<option value="{{ $user->id }}" @selected(request('technician_id')==$user->id)>#{{ $user->id }} · {{ $user->name }}</option>@endforeach</select></label><label class="text-sm font-semibold text-heading">Added By<select name="created_by" class="mt-1.5 w-full rounded-lg border border-border bg-white px-3 py-2.5 font-normal"><option value="">All users</option>@foreach($filterTechnicians as $user)<option value="{{ $user->id }}" @selected(request('created_by')==$user->id)>#{{ $user->id }} · {{ $user->name }}</option>@endforeach</select></label><label class="text-sm font-semibold text-heading">Added From<input type="date" name="date_from" value="{{ request('date_from') }}" class="mt-1.5 w-full rounded-lg border border-border bg-white px-3 py-2.5 font-normal"></label><div class="flex items-end gap-2"><button class="rounded-lg bg-busitema-blue px-4 py-2.5 text-sm font-semibold text-white">Filter</button><a href="{{ route('technician.labs.index') }}" class="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold">Clear</a></div></form></section>
    <div class="flex justify-end"><a href="{{ route('technician.labs.create') }}" class="rounded-lg bg-busitema-gold px-4 py-2.5 text-sm font-semibold text-busitema-navy">Register Computer Lab</a></div>
    <section class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">@forelse($labs as $lab)<article class="rounded-xl border border-border bg-white p-5 shadow-sm"><div class="flex justify-between gap-3"><div><h2 class="text-lg font-semibold">{{ $lab->name }}</h2><p class="mt-1 text-sm text-body-text">{{ $lab->campus?->name }} · {{ $lab->building }}/{{ $lab->room }}</p></div><span class="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-semibold text-busitema-blue">Capacity {{ $lab->capacity }}</span></div><div class="mt-5 grid grid-cols-3 gap-2 text-center"><div class="rounded-lg bg-light-background p-3"><p class="text-xl font-semibold text-heading">{{ $lab->equipment_count }}</p><p class="text-xs">Equipment</p></div><div class="rounded-lg bg-emerald-50 p-3"><p class="text-xl font-semibold text-emerald-700">{{ $lab->operational_count }}</p><p class="text-xs">Operational</p></div><div class="rounded-lg bg-red-50 p-3"><p class="text-xl font-semibold text-red-700">{{ $lab->faulty_count }}</p><p class="text-xs">Faulty</p></div></div><p class="mt-4 text-sm"><span class="text-body-text">Responsible:</span> <strong class="text-heading">{{ $lab->responsibleTechnician?->name ?? 'Not assigned' }}</strong></p><div class="mt-4 rounded-lg bg-light-background p-3 text-xs"><p><strong class="text-heading">Added:</strong> #{{ $lab->created_by ?? '—' }} · {{ $lab->createdBy?->name ?? 'System' }} · {{ $lab->createdBy?->role?->name ?? '—' }}</p><p class="mt-1">{{ $lab->created_at?->format('d M Y H:i') }} · Updated {{ $lab->updated_at?->format('d M Y H:i') }}</p></div><div class="mt-5 flex gap-3"><a href="{{ route('technician.labs.show',$lab) }}" class="font-semibold text-busitema-blue">View lab</a><a href="{{ route('technician.labs.edit',$lab) }}" class="font-semibold text-body-text">Edit</a><a href="{{ route('technician.activity.show',['type'=>'labs','record'=>$lab->id]) }}" class="font-semibold text-body-text">History</a></div></article>@empty<p class="col-span-full rounded-xl border border-border bg-white p-10 text-center">No computer labs are registered in this scope.</p>@endforelse</section>
    {{ $labs->links() }}
</div>
@endsection
