@extends('layouts.app')
@section('title', 'Billing & Invoices | UPAMS')
@section('portal-label', 'Finance & Utilities')
@section('page-heading', 'Billing & Invoices')
@section('content')
@include('admin.partials.flash')
<div class="grid gap-4 sm:grid-cols-3">
    @foreach (['All invoices' => number_format($summary['count']), 'Outstanding value' => 'UGX '.number_format($summary['outstanding']), 'Overdue invoices' => number_format($summary['overdue'])] as $label => $value)
        <div class="rounded-2xl border border-border bg-white p-5 shadow-sm dark:bg-slate-900"><p class="text-xs font-semibold uppercase tracking-wider text-body-text">{{ $label }}</p><p class="mt-2 text-2xl font-bold text-heading">{{ $value }}</p></div>
    @endforeach
</div>
<div class="mt-6 rounded-2xl border border-border bg-white p-5 shadow-sm dark:bg-slate-900">
    <div class="flex flex-wrap items-center justify-between gap-3"><form class="flex flex-1 flex-wrap gap-2"><input class="min-w-52 flex-1 rounded-lg border border-border bg-transparent px-3 py-2" name="q" value="{{ request('q') }}" placeholder="Search reference or beneficiary"><select class="rounded-lg border border-border bg-transparent px-3 py-2" name="campus_id"><option value="">All campuses</option>@foreach($campuses as $campus)<option value="{{ $campus->id }}" @selected(request('campus_id') == $campus->id)>{{ $campus->name }}</option>@endforeach</select><select class="rounded-lg border border-border bg-transparent px-3 py-2" name="status"><option value="">All statuses</option>@foreach(['Draft','Issued','Partially Paid','Paid','Overdue','Cancelled','Archived'] as $status)<option @selected(request('status') === $status)>{{ $status }}</option>@endforeach</select><button class="rounded-lg bg-busitema-blue px-4 py-2 font-semibold text-white">Filter</button></form><a class="rounded-lg border border-border px-4 py-2 font-semibold" href="{{ route('billing.export', request()->query()) }}">Export CSV</a><a class="rounded-lg bg-busitema-gold px-4 py-2 font-semibold text-slate-950" href="{{ route('billing.create') }}">Create invoice</a></div>
    <div class="mt-5 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-border text-xs uppercase text-body-text"><tr><th class="p-3">Invoice</th><th class="p-3">Beneficiary / campus</th><th class="p-3">Due</th><th class="p-3 text-right">Total</th><th class="p-3 text-right">Balance</th><th class="p-3">Status</th><th class="p-3">Updated by / at</th></tr></thead><tbody class="divide-y divide-border">@forelse($invoices as $invoice)<tr class="hover:bg-slate-50 dark:hover:bg-slate-800"><td class="p-3"><a class="font-semibold text-busitema-blue dark:text-sky-300" href="{{ route('billing.show',$invoice) }}">{{ $invoice->reference }}</a></td><td class="p-3">{{ $invoice->beneficiary->full_name_organization }}<br><span class="text-xs text-body-text">{{ $invoice->campus->name }}</span></td><td class="p-3">{{ $invoice->due_date->format('d M Y') }}</td><td class="p-3 text-right">{{ number_format($invoice->total_amount,2) }}</td><td class="p-3 text-right font-semibold">{{ number_format($invoice->balance(),2) }}</td><td class="p-3"><span class="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold dark:bg-slate-700">{{ $invoice->paymentStatus() }}</span></td><td class="p-3 text-xs">{{ $invoice->updater?->name ?? 'System' }}<br>{{ $invoice->updated_at->format('d M Y H:i') }}</td></tr>@empty<tr><td class="p-8 text-center text-body-text" colspan="7">No invoices match these filters.</td></tr>@endforelse</tbody></table></div>
    <div class="mt-5">{{ $invoices->links() }}</div>
</div>
@endsection
