@extends('layouts.app')
@section('title', $invoice->reference.' | UPAMS')
@section('portal-label', 'Finance & Utilities')
@section('page-heading', 'Invoice '.$invoice->reference)
@section('content')
@include('admin.partials.flash')
<div class="flex flex-wrap justify-end gap-2 print:hidden"><button onclick="window.print()" class="rounded-lg border border-border px-4 py-2 font-semibold">Print / PDF</button>@unless(in_array($invoice->status,['Cancelled','Archived']))<a href="{{ route('payments.create',['invoice_id'=>$invoice->id]) }}" class="rounded-lg bg-busitema-blue px-4 py-2 font-semibold text-white">Record payment</a><a href="{{ route('billing.edit',$invoice) }}" class="rounded-lg bg-busitema-gold px-4 py-2 font-semibold text-slate-950">Correct invoice</a>@endunless</div>
<div class="mt-4 rounded-2xl border border-border bg-white p-6 shadow-sm dark:bg-slate-900"><div class="flex flex-wrap justify-between gap-5"><div><p class="text-sm text-body-text">Bill to</p><h2 class="text-xl font-bold">{{ $invoice->beneficiary->full_name_organization }}</h2><p>{{ $invoice->campus->name }}</p></div><div class="text-right"><span class="rounded-full bg-slate-100 px-3 py-1 text-sm font-semibold dark:bg-slate-700">{{ $invoice->paymentStatus() }}</span><p class="mt-3">Issued {{ $invoice->issue_date->format('d M Y') }} · Due {{ $invoice->due_date->format('d M Y') }}</p></div></div><p class="mt-8 border-y border-border py-5">{{ $invoice->description }}</p><div class="ml-auto mt-6 max-w-sm space-y-2"><div class="flex justify-between"><span>Subtotal</span><strong>UGX {{ number_format($invoice->subtotal,2) }}</strong></div><div class="flex justify-between"><span>Tax</span><strong>UGX {{ number_format($invoice->tax_amount,2) }}</strong></div><div class="flex justify-between border-t border-border pt-2 text-lg"><span>Total</span><strong>UGX {{ number_format($invoice->total_amount,2) }}</strong></div><div class="flex justify-between text-emerald-600"><span>Paid</span><strong>UGX {{ number_format($invoice->paidAmount(),2) }}</strong></div><div class="flex justify-between text-xl"><span>Balance</span><strong>UGX {{ number_format($invoice->balance(),2) }}</strong></div></div>
<div class="mt-8 grid gap-3 border-t border-border pt-5 text-xs text-body-text sm:grid-cols-2"><p>Created By: {{ $invoice->creator?->name ?? 'System' }}<br>Created At: {{ $invoice->created_at->format('d M Y H:i') }}</p><p>Last Updated By: {{ $invoice->updater?->name ?? 'System' }}<br>Last Updated At: {{ $invoice->updated_at->format('d M Y H:i') }}</p></div></div>
@unless(in_array($invoice->status,['Cancelled','Archived']))<form method="POST" action="{{ route('billing.archive',$invoice) }}" class="mt-6 rounded-2xl border border-red-200 bg-white p-5 dark:border-red-900 dark:bg-slate-900">@csrf @method('PATCH')<h3 class="font-bold">Archive or cancel invoice</h3><div class="mt-3 flex flex-wrap gap-3"><select name="status" class="rounded-lg border border-border bg-transparent p-3"><option>Archived</option><option>Cancelled</option></select><input name="reason" minlength="10" required class="min-w-64 flex-1 rounded-lg border border-border bg-transparent p-3" placeholder="Mandatory reason"><button class="rounded-lg bg-red-700 px-4 py-2 font-semibold text-white">Confirm</button></div></form>@endunless
@endsection
